name: Deploy to InfinityFree FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy to InfinityFree Hosting
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 📂 Sync files to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_38464190
          password: 'Dhaniel0'
          server-dir: returninboundieg.great-site.net/htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**
            **/node_modules/**
            **/jalankan-server.bat
            **/*.sql
            **/deploy-to-infinity.ps1
